In [37]:
# importing pandas
import pandas as pd

pd.__version__

'2.2.2'

Loading the data

In [38]:
#loading the data from the csv file to a data frame 
df=pd.read_csv('data.csv')

Exploring data

In [39]:
#exploring data 

#displays first 5 rows
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [40]:
#display last 5 rows
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [41]:
#random rows from the dataset 
df.sample(5)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
601,17355884,Mast & Harbour,Men Green & Navy Blue Checked Pure Cotton Casu...,4.1,167,1999,65.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":13,""2_stars"":3,""3_stars"":19,""4_stars...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",PRE███R A███REL███,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",NaN,"NO ███3, ███EME█████████D, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
147,13703862,Style Quotient,Women Olive Green Solid Shirt Dress,3.9,46,1749,71.0,"""₹507.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":6,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Kri███n S███het█████████td,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,"615███hur███ate█████████,5 ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
366,19015534,U.S. Polo Assn. Kids,Girls Maroon Solid Puffer Jacket,4.1,33,2499,36.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":5,""4_stars"":...",NaN,ARV███ LI███TYL█████████LIM██████,"[{""size"":""1-2Y"",""value"":""23.23in"",""value_name""...","[""https://videos.myntassets.com/assets/videos/...",10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
492,15749326,W,Women Maroon Solid Crinkled Effect Cropped Eth...,3.6,24,1499,65.0,"""₹740.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":3,""2_stars"":3,""3_stars"":5,""4_stars"":...",NaN,Esh███ox ███mme█████████td,"[{""size"":""28"",""value"":""43.0in"",""value_name"":""H...",NaN,Vil███e B███a B█████████ata███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos
139,20040576,U&F,Olive Green Crepe Maxi Dress,3.8,23,2899,68.0,"""₹927.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":2,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",SVP███XPO███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,"A-4███ect███7 N█████████ , █████████████████████1",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [42]:
# no of rows and columns in the data set
df.shape

(1000, 24)

In [43]:
#structural summary of the data 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [45]:
#statistical summary of the data 
# mean,mediam,standard deviation,min,max and Quartiles
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [46]:
#categorical columns summary
# top frequent values, unique values and also counts 
df.describe(include='object')

,title,product_description,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,427,699,1000,219,699,438,1000,1000,1000
unique,454,989,466,1,1000,16,998,658,967,808,302,301,672,219,298,22,468,159,97
top,Roadster,Women Pink Solid Top,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""A pair of navy blue running sp...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Blouse"",""specification...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on IndusI...",tops
freq,30,3,25,1000,1,650,2,16,4,114,27,40,135,1,40,126,306,265,122

In [47]:
#columns from the dataset
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [48]:
#data type of each column from the dataset
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

Handling Missing Values

In [49]:
#handling missing values
#missing values in each column
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [50]:
'''
the columns having null values are discount,what_customers_said, 
seller_name,videos ,seller_information and variantions
%of missing values of discount =12.1%
%of missing values of what_customers_said= 57.3%
%of missing values of seller_name=30.1%
%of missing values of videos=78.1%
%of missing values of seller_infomation=30.1%
%of missing values of variations=56.2
 '''

#filling null data
#filling discount with median
df["discount"] = df["discount"].fillna(df["discount"].median())

In [51]:
#seller_columns non null values
print(df["seller_name"].sample(10))

129                            Vis███ St███
666                            Sup███om ███
745                                     NaN
218                   A&V███WEL███VT ██████
704                      Omn███ch ███ail███
250                           ITS███FFE███T
490                                   Q-ONE
348                Kap███s R███il █████████
899                                     NaN
553    SPY███ LI███TYL█████████E L█████████
Name: seller_name, dtype: object

In [52]:
#handling missing value of seller_name
df["seller_name"] = df["seller_name"].fillna("Unknown Seller")

In [53]:
#displaying seller_information column
print(df["seller_information"].sample(10))

806                                                  NaN
920                                                  NaN
162                                                  NaN
274    11t███loo███Fla█████████6, ███████████████████...
460    B-4███/40███402█████████38/███████████████████...
947                                                  NaN
772                                                  NaN
423    Blo███B-1███abi█████████-24███████████████████...
626                                                  NaN
878                                                  NaN
Name: seller_information, dtype: object

In [54]:
#handling missing values for seller_information
df["seller_information"] = df["seller_information"].fillna("Information not Found")

In [55]:
#display sample data of what_customer_said column
print(df['what_customers_said'].dtype) #object

#example data 
print(df[df["what_customers_said"].notna()]["what_customers_said"])

object
23     [{"percentage":"100","value_name":"Fit, Just R...
42     [{"percentage":"100","value_name":"Fit, Just R...
46     [{"percentage":"40","value_name":"Fit, A Littl...
48     [{"percentage":"100","value_name":"Fit, Just R...
51     [{"percentage":"70","value_name":"Fit, Just Ri...
                             ...
966    [{"percentage":"96","value_name":"Fit, Just Ri...
968    [{"percentage":"100","value_name":"Fit, A Litt...
969    [{"percentage":"50","value_name":"Fit, Just Ri...
970    [{"percentage":"67","value_name":"Fit, Just Ri...
971    [{"percentage":"67","value_name":"Fit, Just Ri...
Name: what_customers_said, Length: 427, dtype: object

In [56]:
#despite having 50%+ null values as we cannot ignore the feedback from the customers as they are 
#core business logic 
#handling the null values by adding an indicator flag (feature engineering !!)

#creating a indicator column as has_customer_reviews
df["has_customer_reviews"]=df['what_customers_said'].notna().astype(int)

#filling the null values with an empty list to preserve sturcture
df["what_customers_said"] = df["what_customers_said"].fillna("[]")

# Verify
print(df["what_customers_said"].isnull().sum())

#view the result
df[['what_customers_said', 'has_customer_reviews']].sample(10)

0

                                   what_customers_said  has_customer_reviews
720                                                 []                     0
564  [{"percentage":"50","value_name":"Fit, Tight"}...                     1
901  [{"percentage":"67","value_name":"Fit, Just Ri...                     1
38                                                  []                     0
921                                                 []                     0
138                                                 []                     0
275                                                 []                     0
99                                                  []                     0
192                                                 []                     0
546                                                 []                     0

In [61]:
#sample data of vide0s and variations column which are not null
print(df["videos"].sample(10))

103                                                  NaN
849                                                  NaN
567                                                  NaN
673                                                  NaN
453                                                  NaN
760    ["https://videos.myntassets.com/assets/videos/...
502                                                  NaN
225                                                  NaN
990    ["rw-9053317_cae700","https://videos.myntasset...
488                                                  NaN
Name: videos, dtype: object

In [62]:
#dropping videos column as doesnt effect the actual analysis of the data
df=df.drop(columns=["videos"])

#verification 
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category', 'has_customer_reviews'],
      dtype='object')

In [63]:
#sample data of variations column
print(df["variations"].sample(10))

893                                           [{},{},{}]
330                                              [{},{}]
526                               [{},{},{},{},{},{},{}]
305                                                  NaN
493    [{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...
617                                                  NaN
136                                                  NaN
523                            [{},{},{},{},{},{},{},{}]
113                                              [{},{}]
93                                                   NaN
Name: variations, dtype: object

In [64]:
#dropping the variations column as there is no valid data
df=df.drop(columns=["variations"])

print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'best_offer',
       'more_offers', 'category', 'has_customer_reviews'],
      dtype='object')

In [65]:
df.isnull().sum()
#all null values have been handled

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
seller_information        0
best_offer                0
more_offers               0
category                  0
has_customer_reviews      0
dtype: int64